#!/usr/bin/env bash
# tx-node 一键部署脚本（docker compose）
# 用法: bash <(curl -fsSL https://raw.githubusercontent.com/PaiMonCai/TX-Node/main/deploy.sh)
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

APP_NAME="tx-node"
INSTALL_DIR="/etc/xboard-node"
COMPOSE_FILE="$INSTALL_DIR/docker-compose.yml"
CONFIG_FILE="$INSTALL_DIR/config.yml"
IMAGE="ghcr.io/paimoncai/tx-node:latest"

info()  { echo -e "${CYAN}[*]${NC} $*"; }
ok()    { echo -e "${GREEN}[✓]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
fail()  { echo -e "${RED}[✗]${NC} $*" >&2; exit 1; }

confirm() { # confirm <prompt> <default Y|n>
  local prompt="$1" default="${2:-Y}" reply
  if [ "$default" = "Y" ]; then prompt="$prompt [Y/n] "; else prompt="$prompt [y/N] "; fi
  read -r -p "$prompt" reply || true
  reply="${reply:-$default}"
  [[ "$reply" =~ ^[Yy]$ ]]
}

# ── Step 0: 权限与系统 ──────────────────────────────────────────────
[ "$(id -u)" -eq 0 ] || fail "请用 root 运行（或 sudo bash ...）"
[ -d /etc ] || fail "仅支持 Linux"
echo -e "${BOLD}== tx-node 一键部署 ==${NC}"
echo "镜像: $IMAGE"
echo

# ── Step 1: Docker 环境 ─────────────────────────────────────────────
ensure_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    ok "Docker 环境就绪: $(docker --version | head -1)"
    return
  fi
  warn "未检测到可用的 docker / docker compose 插件"
  if confirm "自动安装 Docker（get.docker.com 官方脚本）？" "Y"; then
    info "安装 Docker..."
    curl -fsSL https://get.docker.com | bash
    systemctl enable --now docker 2>/dev/null || true
    docker compose version >/dev/null 2>&1 || fail "docker compose 插件不可用，请手动安装后重跑"
    ok "Docker 安装完成"
  else
    fail "请先手动安装 Docker + compose 插件后重跑本脚本"
  fi
}
ensure_docker

# ── Step 2: 已有部署检测（幂等）─────────────────────────────────────
if [ -f "$COMPOSE_FILE" ] || docker ps -a --format '{{.Names}}' | grep -qx "$APP_NAME"; then
  warn "检测到已有 tx-node 部署（$INSTALL_DIR）"
  echo "  1) 升级镜像并重启"
  echo "  2) 重新配置（覆盖 config.yml，旧配置自动备份）"
  echo "  3) 卸载（保留配置备份）"
  echo "  4) 取消"
  read -r -p "选择 [1-4]: " choice
  case "$choice" in
    1)
      info "升级镜像..."
      docker compose -f "$COMPOSE_FILE" pull
      docker compose -f "$COMPOSE_FILE" up -d
      ok "已升级并重启"
      exit 0
      ;;
    2) info "进入重新配置流程" ;;
    3)
      if confirm "确认卸载 tx-node（容器删除，配置备份保留）？" "n"; then
        docker compose -f "$COMPOSE_FILE" down 2>/dev/null || docker rm -f "$APP_NAME" 2>/dev/null || true
        mv "$COMPOSE_FILE" "$COMPOSE_FILE.uninstalled.$(date +%s)" 2>/dev/null || true
        ok "已卸载。配置保留在 $INSTALL_DIR（compose 文件已改名停用）"
        exit 0
      fi
      exit 0
      ;;
    *) echo "已取消"; exit 0 ;;
  esac
fi

# ── Step 3: 交互式配置 ──────────────────────────────────────────────
echo
info "配置向导（面板信息可在 Xboard 后台查到）"

read -r -p "面板地址 (https://panel.example.com): " PANEL_URL
PANEL_URL="${PANEL_URL%/}"
[[ "$PANEL_URL" =~ ^https?:// ]] || fail "面板地址必须以 http:// 或 https:// 开头"

echo "运行模式:"
echo "  1) node    —— 单个节点（面板里这台就是一个节点）"
echo "  2) machine —— 整机模式（接管面板上绑定到这台机器的所有节点）"
read -r -p "选择 [1/2] (默认 1): " MODE
MODE="${MODE:-1}"

MACHINE_ID=""
NODE_ID=""
if [ "$MODE" = "2" ]; then
  read -r -p "machine_id（面板 → 机器管理里的 ID）: " MACHINE_ID
  [[ "$MACHINE_ID" =~ ^[0-9]+$ ]] && [ "$MACHINE_ID" -gt 0 ] || fail "machine_id 必须是正整数"
  read -r -s -p "machine token（机器令牌，输入不回显）: " MACHINE_TOKEN; echo
  [ -n "$MACHINE_TOKEN" ] || fail "machine token 不能为空"
else
  read -r -p "node_id（面板 → 节点列表里的 ID）: " NODE_ID
  [[ "$NODE_ID" =~ ^[0-9]+$ ]] && [ "$NODE_ID" -gt 0 ] || fail "node_id 必须是正整数"
  read -r -s -p "server_token（节点通讯密钥，输入不回显）: " NODE_TOKEN; echo
  [ -n "$NODE_TOKEN" ] || fail "server_token 不能为空"
fi

read -r -p "内核类型 [singbox/xray] (默认 singbox): " KERNEL
KERNEL="${KERNEL:-singbox}"
[[ "$KERNEL" =~ ^(singbox|xray)$ ]] || fail "内核只支持 singbox 或 xray"

AUDIT_ENABLED="false"
if [ "$KERNEL" = "singbox" ]; then
  if confirm "启用访问审计（需面板已安装 AccessAudit 插件 v2.0+）？" "Y"; then
    AUDIT_ENABLED="true"
  fi
else
  warn "xray 内核不支持内嵌审计；如需审计请使用 AccessAudit 插件自带的 audit-agent.py（旁路 tail access log）"
fi

read -r -p "日志级别 [info/debug/warn/error] (默认 info): " LOG_LEVEL
LOG_LEVEL="${LOG_LEVEL:-info}"

# ── Step 4: 写配置 ──────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"
if [ -f "$CONFIG_FILE" ]; then
  cp -a "$CONFIG_FILE" "$CONFIG_FILE.bak.$(date +%s)"
  info "旧配置已备份"
fi

if [ "$MODE" = "2" ]; then
  PANEL_BLOCK=$(cat <<EOF
panel:
  url: "$PANEL_URL"
machine:
  machine_id: $MACHINE_ID
  token: "$MACHINE_TOKEN"
EOF
)
else
  PANEL_BLOCK=$(cat <<EOF
panel:
  url: "$PANEL_URL"
  token: "$NODE_TOKEN"
  node_id: $NODE_ID
EOF
)
fi

cat > "$CONFIG_FILE" <<EOF
# Generated by tx-node deploy.sh ($(date '+%Y-%m-%d %H:%M:%S'))
$PANEL_BLOCK

kernel:
  type: "$KERNEL"

log:
  level: "$LOG_LEVEL"

# tx-node 访问审计（sing-box 内核）。删除本段或 enabled: false 即关闭。
audit:
  enabled: $AUDIT_ENABLED
EOF
chmod 600 "$CONFIG_FILE"
ok "配置已写入 $CONFIG_FILE（权限 600）"

cat > "$COMPOSE_FILE" <<EOF
services:
  tx-node:
    image: $IMAGE
    container_name: $APP_NAME
    restart: always
    network_mode: host
    volumes:
      - $CONFIG_FILE:/etc/xboard-node/config.yml:ro
EOF
ok "compose 文件已写入 $COMPOSE_FILE"

# ── Step 5: 拉镜像 + 启动 ───────────────────────────────────────────
info "拉取镜像（首次较慢）..."
docker compose -f "$COMPOSE_FILE" pull || fail "镜像拉取失败。若是私有包未授权，请先 docker login ghcr.io；网络问题可配置镜像加速后重跑本脚本"

info "启动..."
docker compose -f "$COMPOSE_FILE" up -d

sleep 5
docker ps --format '{{.Names}} {{.Status}}' | grep -q "$APP_NAME.*Up" || {
  warn "容器未正常运行，最近日志："
  docker logs --tail 20 "$APP_NAME" || true
  fail "启动失败，请根据上方日志排查后重跑本脚本"
}
ok "容器运行中"

# ── Step 6: 部署后验证 ──────────────────────────────────────────────
if [ "$AUDIT_ENABLED" = "true" ]; then
  sleep 5
  if docker logs "$APP_NAME" 2>&1 | grep -q "audit reporter enabled"; then
    ok "审计模块已启用并连接面板"
  else
    warn "未在日志中看到 'audit reporter enabled'，请检查: docker logs $APP_NAME"
  fi
fi

echo
echo -e "${BOLD}== 部署完成 ==${NC}"
echo "常用命令:"
echo "  查看日志:  docker logs -f $APP_NAME"
echo "  重启:      docker compose -f $COMPOSE_FILE restart"
echo "  升级:      docker compose -f $COMPOSE_FILE pull && docker compose -f $COMPOSE_FILE up -d"
echo "  改配置:    vim $CONFIG_FILE && docker compose -f $COMPOSE_FILE restart"
if [ "$AUDIT_ENABLED" = "true" ]; then
  echo
  echo "面板侧下一步: /plugin/access-audit 配置审计规则，命中记录与节点状态会在管理页展示"
fi
